# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obn_planner_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBNPlannerDockWidgetBase(object):
    def setupUi(self, OBNPlannerDockWidgetBase):
        OBNPlannerDockWidgetBase.setObjectName("OBNPlannerDockWidgetBase")
        OBNPlannerDockWidgetBase.resize(347, 477)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importSpsButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.importSpsButton.setObjectName("importSpsButton")
        self.verticalLayout.addWidget(self.importSpsButton)
        OBNPlannerDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(OBNPlannerDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(OBNPlannerDockWidgetBase)

    def retranslateUi(self, OBNPlannerDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        OBNPlannerDockWidgetBase.setWindowTitle(_translate("OBNPlannerDockWidgetBase", "OBN Source Line Planner & Optimisation"))
        self.importSpsButton.setText(_translate("OBNPlannerDockWidgetBase", "Import SPS File..."))
        self.editFinalizeButton.setText(_translate("OBNPlannerDockWidgetBase", "Edit Sequence / Finalize Plan"))
