# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OBNPlannerDockWidget
                                  A QGIS plugin
 Automates, streamlines, and optimizes the planning process for Ocean Bottom Node (OBN) seismic survey source lines.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Muhammad Aldien Said
        email                : aldien03@gmail.com
 ***************************************************************************/

/***************************************************************************
 * *
 * This program is free software; you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation; either version 2 of the License, or     *
 * (at your option) any later version.                                   *
 * *
 ***************************************************************************/
"""

import os

# --- QGIS Imports ---
from qgis.core import (
    QgsMessageLog,
    Qgis,
    QgsVectorLayer,
    QgsVectorFileWriter,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsPointXY,
    QgsGeometry, # Added QgsGeometry import for clarity
    QgsProject,
    QgsCoordinateReferenceSystem,
    QgsWkbTypes # For geometry type
)
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, QVariant # QVariant for field types
from qgis.PyQt.QtWidgets import QFileDialog

# --- Compiled UI Import ---
from .obn_planner_dockwidget_ui import Ui_OBNPlannerDockWidgetBase


class OBNPlannerDockWidget(QtWidgets.QDockWidget, Ui_OBNPlannerDockWidgetBase):

    closingPlugin = pyqtSignal()

    # Store the last used directory path
    last_sps_dir = os.path.expanduser("~")
    last_gpkg_dir = os.path.expanduser("~") # For saving the layer

    def __init__(self, parent=None):
        """Constructor."""
        super(OBNPlannerDockWidget, self).__init__(parent)
        self.setupUi(self)

        # --- Connect Signals to Slots ---
        self.importSpsButton.clicked.connect(self.handle_sps_import_button)


    # --- Slot Methods ---
    def handle_sps_import_button(self):
        """
        Handles the 'Import SPS File...' button click. Opens a file dialog
        and then calls the parsing/loading function if a file is selected.
        """
        QgsMessageLog.logMessage("Attempting to open file dialog for SPS import.", "OBN Planner Plugin", level=Qgis.Info)

        sps_file_filter = "SPS Files (*.sps *.s00 *.s01 *.txt);;All Files (*)"
        sps_file_path, _ = QFileDialog.getOpenFileName(
            self, "Select SPS Pre-plot File", self.last_sps_dir, sps_file_filter
        )

        if sps_file_path:
            QgsMessageLog.logMessage(f"User selected SPS file: {sps_file_path}", "OBN Planner Plugin", level=Qgis.Info)
            self.last_sps_dir = os.path.dirname(sps_file_path)

            # --- Call the function to parse the file and create the layer ---
            self.parse_and_load_sps(sps_file_path) # Pass the selected file path

        else:
            QgsMessageLog.logMessage("User cancelled SPS file selection.", "OBN Planner Plugin", level=Qgis.Info)

    def parse_and_load_sps(self, sps_file_path):
        """
        Parses the selected SPS file and loads the data into a new
        QGIS GeoPackage layer.

        :param sps_file_path: Full path to the SPS file to parse.
        :type sps_file_path: str
        """
        QgsMessageLog.logMessage(f"Starting SPS parsing for: {sps_file_path}", "OBN Planner Plugin", level=Qgis.Info)

        parsed_data = []
        error_log = []
        line_count = 0
        skip_headers = 36 # As per PRD [F-DH-01]

        # --- 1. Parse the SPS File ---
        try:
            # Specify encoding='latin-1'
            with open(sps_file_path, 'r', encoding='latin-1') as f:
                for line in f:
                    line_count += 1
                    if line_count <= skip_headers:
                        continue # Skip header lines

                    line = line.rstrip() # Remove trailing whitespace

                    if len(line) < 65:
                        error_log.append(f"Line {line_count}: Skipped short line.")
                        continue

                    try:
                        # Extract data based on fixed-width columns
                        line_num_str = line[1:5].strip()
                        sp_str = line[21:25].strip()
                        easting_str = line[48:56].strip()
                        northing_str = line[57:65].strip()

                        if not line_num_str or not sp_str or not easting_str or not northing_str:
                            raise ValueError("Missing required field(s)")

                        line_num = int(line_num_str)
                        sp = int(sp_str)
                        easting = float(easting_str)
                        northing = float(northing_str)

                        parsed_data.append({
                            'line': line_num, 'sp': sp,
                            'e': easting, 'n': northing
                        })

                    except (ValueError, IndexError) as e:
                        error_log.append(f"Line {line_count}: Error parsing '{line[:70]}...' - {e}")

        except UnicodeDecodeError as ude:
             error_msg = f"Encoding Error: Could not read file with 'latin-1'. Try another encoding? Error: {ude}"
             QgsMessageLog.logMessage(error_msg, "OBN Planner Plugin", level=Qgis.Critical)
             QtWidgets.QMessageBox.critical(self, "File Encoding Error", error_msg)
             return
        except FileNotFoundError:
            QgsMessageLog.logMessage(f"Error: SPS file not found at {sps_file_path}", "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.critical(self, "File Not Found", f"Could not find the specified SPS file:\n{sps_file_path}")
            return
        except Exception as e:
            QgsMessageLog.logMessage(f"Error reading SPS file: {e}", "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.critical(self, "File Read Error", f"An error occurred while reading the SPS file:\n{e}")
            return

        if error_log:
            QgsMessageLog.logMessage(f"SPS Parsing completed with {len(error_log)} errors/warnings.", "OBN Planner Plugin", level=Qgis.Warning)
            for err in error_log[:10]:
                 QgsMessageLog.logMessage(err, "OBN Planner Plugin", level=Qgis.Warning)
            if len(error_log) > 10:
                 QgsMessageLog.logMessage("... (further errors truncated in log)", "OBN Planner Plugin", level=Qgis.Warning)

        if not parsed_data:
            QgsMessageLog.logMessage("No valid data points parsed from the SPS file.", "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.warning(self, "Parsing Failed", "Could not parse any valid data points from the selected SPS file.")
            return

        QgsMessageLog.logMessage(f"Successfully parsed {len(parsed_data)} data points.", "OBN Planner Plugin", level=Qgis.Info)

        # --- 2. Get Output Layer Path ---
        gpkg_filter = "GeoPackage (*.gpkg)"
        output_path, _ = QFileDialog.getSaveFileName(
            self, "Save SPS Data as GeoPackage Layer", self.last_gpkg_dir, gpkg_filter
        )

        if not output_path:
            QgsMessageLog.logMessage("User cancelled saving the output layer.", "OBN Planner Plugin", level=Qgis.Info)
            return

        if not output_path.lower().endswith(".gpkg"):
            output_path += ".gpkg"

        self.last_gpkg_dir = os.path.dirname(output_path)

        # --- 3. Define Layer Fields and CRS ---
        fields = QgsFields()
        fields.append(QgsField("LineNum", QVariant.Int, "Integer"))
        fields.append(QgsField("SP", QVariant.Int, "Integer"))
        fields.append(QgsField("Easting", QVariant.Double, "Double"))
        fields.append(QgsField("Northing", QVariant.Double, "Double"))
        fields.append(QgsField("Status", QVariant.String, "String", 20))
        fields.append(QgsField("Heading", QVariant.Double, "Double"))

        crs = QgsProject.instance().crs()
        if not crs.isValid():
            QgsMessageLog.logMessage("Project CRS is invalid. Cannot create layer.", "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.critical(self, "Invalid CRS", "The current QGIS project CRS is invalid. Please set a valid project CRS before importing.")
            return

        # --- 4. Create and Populate the GeoPackage Layer ---
        writer = QgsVectorFileWriter(
            output_path, "UTF-8", fields, QgsWkbTypes.Point, crs, "GPKG"
        )

        if writer.hasError() != QgsVectorFileWriter.NoError:
            error_msg = f"Error creating GeoPackage file: {writer.errorMessage()}"
            QgsMessageLog.logMessage(error_msg, "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.critical(self, "Layer Creation Error", error_msg)
            return

        feature = QgsFeature(fields)
        points_added = 0
        for point_data in parsed_data:
            # Create QgsPointXY from coordinates
            point_xy = QgsPointXY(point_data['e'], point_data['n'])
            # *** MODIFIED PART: Create QgsGeometry from QgsPointXY ***
            geometry = QgsGeometry.fromPointXY(point_xy)
            # Set the QgsGeometry on the feature
            feature.setGeometry(geometry)

            # Set attributes
            feature.setAttribute("LineNum", point_data['line'])
            feature.setAttribute("SP", point_data['sp'])
            feature.setAttribute("Easting", point_data['e'])
            feature.setAttribute("Northing", point_data['n'])
            feature.setAttribute("Status", "To Be Acquired")
            feature.setAttribute("Heading", None)

            if writer.addFeature(feature) == False:
                 error_msg = f"Error adding feature for Line {point_data['line']}, SP {point_data['sp']}: {writer.errorMessage()}"
                 QgsMessageLog.logMessage(error_msg, "OBN Planner Plugin", level=Qgis.Warning)
            else:
                points_added += 1

        del writer

        QgsMessageLog.logMessage(f"Finished writing GeoPackage. {points_added}/{len(parsed_data)} points added.", "OBN Planner Plugin", level=Qgis.Info)

        # --- 5. Add the Layer to QGIS Project ---
        layer_name = os.path.splitext(os.path.basename(output_path))[0]
        layer = QgsVectorLayer(output_path, layer_name, "ogr")

        if not layer.isValid():
            error_msg = f"Failed to load the created layer: {output_path}"
            QgsMessageLog.logMessage(error_msg, "OBN Planner Plugin", level=Qgis.Critical)
            QtWidgets.QMessageBox.critical(self, "Layer Load Error", error_msg)
        else:
            QgsProject.instance().addMapLayer(layer)
            QgsMessageLog.logMessage(f"Layer '{layer_name}' added to project.", "OBN Planner Plugin", level=Qgis.Success)


    # --- END: Slot Methods ---

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

